# Generated by Django 5.2.17 on 2026-09-29 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('application_status', 'Application Status'), ('interview_invite', 'Interview Invitation'), ('new_application', 'New Applicant'), ('job_alert', 'Job Alert'), ('message', 'New Message'), ('recommendation', 'Job Recommendation'), ('system', 'System Notification')], default='system', max_length=30)),
                ('action_url', models.CharField(blank=True, default='', max_length=300)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_application_updates', models.BooleanField(default=True)),
                ('email_interviews', models.BooleanField(default=True)),
                ('email_job_recommendations', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
