# Generated by Django 5.2.17 on 2026-09-29 10:11

import apps.candidates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, default='Full Stack Software Engineer', max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=2)),
                ('preferred_location', models.CharField(blank=True, default='Remote', max_length=255)),
                ('preferred_employment_type', models.CharField(blank=True, default='full_time', max_length=50)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('portfolio_url', models.URLField(blank=True, max_length=300)),
                ('github_url', models.URLField(blank=True, max_length=300)),
                ('linkedin_url', models.URLField(blank=True, max_length=300)),
                ('website_url', models.URLField(blank=True, max_length=300)),
                ('is_open_to_work', models.BooleanField(default=True)),
                ('profile_strength', models.PositiveIntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=150)),
                ('credential_url', models.URLField(blank=True, max_length=300)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='candidates.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=150)),
                ('field_of_study', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('workplace_type', models.CharField(default='hybrid', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to='candidates.candidateprofile')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('project_url', models.URLField(blank=True, max_length=300)),
                ('repository_url', models.URLField(blank=True, max_length=300)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/', validators=[apps.candidates.models.validate_resume_file])),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('file_size_kb', models.PositiveIntegerField(default=0)),
                ('file_extension', models.CharField(default='pdf', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['-is_default', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Software Engineer Resume', max_length=200)),
                ('template_name', models.CharField(default='modern', max_length=50)),
                ('theme_color', models.CharField(default='#2563eb', max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='built_resumes', to='candidates.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=30)),
                ('years_of_experience', models.PositiveIntegerField(default=1)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='candidates.candidateprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='jobs.skill')),
            ],
            options={
                'unique_together': {('candidate', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
