# Generated by Django 5.2.17 on 2026-09-29 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('icon', models.CharField(default='Briefcase', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('category', models.CharField(blank=True, default='General', max_length=100)),
                ('is_trending', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('department', models.CharField(blank=True, default='Engineering', max_length=120)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('remote', 'Remote')], db_index=True, default='full_time', max_length=30)),
                ('workplace_type', models.CharField(choices=[('on_site', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], db_index=True, default='hybrid', max_length=30)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('is_salary_negotiable', models.BooleanField(default=False)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-1 yrs)'), ('junior', 'Junior (1-3 yrs)'), ('mid', 'Mid Level (3-5 yrs)'), ('senior', 'Senior (5-8 yrs)'), ('lead', 'Lead / Principal (8+ yrs)'), ('executive', 'Executive / VP')], db_index=True, default='mid', max_length=30)),
                ('education_level', models.CharField(blank=True, default="Bachelor's Degree in Computer Science or related field", max_length=150)),
                ('description', models.TextField()),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused'), ('closed', 'Closed'), ('expired', 'Expired')], db_index=True, default='published', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.company')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.jobcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', 'Fraud or Scam'), ('fake_company', 'Fake Company or Impersonation'), ('misleading_salary', 'Misleading Salary / Job Details'), ('inappropriate', 'Inappropriate or Discriminatory Content'), ('duplicate', 'Duplicate Listing'), ('other', 'Other Violation')], max_length=40)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('resolved', 'Resolved / Action Taken'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20)),
                ('admin_action_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.job')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_jobs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_jobs', to='jobs.skill')),
            ],
            options={
                'unique_together': {('job', 'skill')},
            },
        ),
    ]
